const food = {
  recipes: [
    {
      vegetarian: true,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      weightWatcherSmartPoints: 10,
      gaps: "no",
      lowFodmap: false,
      preparationMinutes: 40,
      cookingMinutes: 70,
      aggregateLikes: 35,
      spoonacularScore: 90.0,
      healthScore: 31.0,
      creditsText: "BBC Good Food",
      sourceName: "BBC Good Food",
      pricePerServing: 69.8,
      extendedIngredients: [
        {
          id: 18374,
          aisle: "Refrigerated",
          image: "yeast-fresh.jpg",
          consistency: "solid",
          name: "fresh yeast",
          original: "10g fresh yeast or 7g sachet dried",
          originalString: "10g fresh yeast or 7g sachet dried",
          originalName: "fresh yeast or 7g sachet dried",
          amount: 10.0,
          unit: "g",
          meta: ["dried", "fresh"],
          metaInformation: ["dried", "fresh"],
          measures: {
            us: { amount: 0.353, unitShort: "oz", unitLong: "ounces" },
            metric: { amount: 10.0, unitShort: "g", unitLong: "grams" },
          },
        },
        {
          id: 19335,
          aisle: "Baking",
          image: "sugar-in-bowl.png",
          consistency: "solid",
          name: "sugar",
          original: "½ tsp sugar",
          originalString: "½ tsp sugar",
          originalName: "sugar",
          amount: 0.5,
          unit: "tsp",
          meta: [],
          metaInformation: [],
          measures: {
            us: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
            metric: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
          },
        },
        {
          id: 20081,
          aisle: "Baking",
          image: "flour.png",
          consistency: "solid",
          name: "flour",
          original: "375g Italian '00' flour, plus extra for dusting",
          originalString: "375g Italian '00' flour, plus extra for dusting",
          originalName: "Italian '00' flour, plus extra for dusting",
          amount: 375.0,
          unit: "g",
          meta: ["italian", "for dusting"],
          metaInformation: ["italian", "for dusting"],
          measures: {
            us: { amount: 13.228, unitShort: "oz", unitLong: "ounces" },
            metric: { amount: 375.0, unitShort: "g", unitLong: "grams" },
          },
        },
        {
          id: 4053,
          aisle: "Oil, Vinegar, Salad Dressing",
          image: "olive-oil.jpg",
          consistency: "liquid",
          name: "olive oil",
          original: "1 tbsp olive oil, plus extra for greasing",
          originalString: "1 tbsp olive oil, plus extra for greasing",
          originalName: "olive oil, plus extra for greasing",
          amount: 1.0,
          unit: "tbsp",
          meta: ["for greasing"],
          metaInformation: ["for greasing"],
          measures: {
            us: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
            metric: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
          },
        },
        {
          id: 93790,
          aisle: "Cheese",
          image: "mozzarella-balls.jpg",
          consistency: "solid",
          name: "mozzarella balls",
          original: "3 x 125g balls mozzarella, torn",
          originalString: "3 x 125g balls mozzarella, torn",
          originalName: "x 125g balls mozzarella, torn",
          amount: 3.0,
          unit: "",
          meta: [],
          metaInformation: [],
          measures: {
            us: { amount: 3.0, unitShort: "", unitLong: "" },
            metric: { amount: 3.0, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 2044,
          aisle: "Produce;Spices and Seasonings",
          image: "basil.jpg",
          consistency: "solid",
          name: "fresh basil",
          original: "fresh basil, to serve",
          originalString: "fresh basil, to serve",
          originalName: "fresh basil, to serve",
          amount: 1.0,
          unit: "serving",
          meta: ["fresh"],
          metaInformation: ["fresh"],
          measures: {
            us: { amount: 1.0, unitShort: "serving", unitLong: "serving" },
            metric: { amount: 1.0, unitShort: "serving", unitLong: "serving" },
          },
        },
        {
          id: 4053,
          aisle: "Oil, Vinegar, Salad Dressing",
          image: "olive-oil.jpg",
          consistency: "liquid",
          name: "olive oil",
          original: "3 tbsp olive oil",
          originalString: "3 tbsp olive oil",
          originalName: "olive oil",
          amount: 3.0,
          unit: "tbsp",
          meta: [],
          metaInformation: [],
          measures: {
            us: { amount: 3.0, unitShort: "Tbsps", unitLong: "Tbsps" },
            metric: { amount: 3.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          },
        },
        {
          id: 11282,
          aisle: "Produce",
          image: "brown-onion.png",
          consistency: "solid",
          name: "onion",
          original: "1 onion, chopped",
          originalString: "1 onion, chopped",
          originalName: "onion, chopped",
          amount: 1.0,
          unit: "",
          meta: ["chopped"],
          metaInformation: ["chopped"],
          measures: {
            us: { amount: 1.0, unitShort: "", unitLong: "" },
            metric: { amount: 1.0, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 11215,
          aisle: "Produce",
          image: "garlic.png",
          consistency: "solid",
          name: "garlic clove",
          original: "1 garlic clove, crushed",
          originalString: "1 garlic clove, crushed",
          originalName: "garlic clove, crushed",
          amount: 1.0,
          unit: "",
          meta: ["crushed"],
          metaInformation: ["crushed"],
          measures: {
            us: { amount: 1.0, unitShort: "", unitLong: "" },
            metric: { amount: 1.0, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 11529,
          aisle: "Produce",
          image: "tomato.png",
          consistency: "solid",
          name: "tomatoes",
          original: "2 x 400g cans good-quality Italian chopped tomatoes",
          originalString: "2 x 400g cans good-quality Italian chopped tomatoes",
          originalName: "x 400g cans good-quality Italian chopped tomatoes",
          amount: 2.0,
          unit: "",
          meta: ["italian", "chopped", "canned"],
          metaInformation: ["italian", "chopped", "canned"],
          measures: {
            us: { amount: 2.0, unitShort: "", unitLong: "" },
            metric: { amount: 2.0, unitShort: "", unitLong: "" },
          },
        },
      ],
      id: 210327,
      title: "Pizza",
      readyInMinutes: 240,
      servings: 6,
      sourceUrl: "https://www.bbcgoodfood.com/recipes/291609/pizza",
      image: "https://spoonacular.com/recipeImages/210327-556x370.jpg",
      imageType: "jpg",
      summary:
        'You can never have too many Mediterranean recipes, so give Pizzan a try. This lacto ovo vegetarian recipe serves 6 and costs <b>70 cents per serving</b>. One portion of this dish contains approximately <b>10g of protein</b>, <b>13g of fat</b>, and a total of <b>364 calories</b>. A couple people made this recipe, and 35 would say it hit the spot. A mixture of olive oil, sugar, flour, and a handful of other ingredients are all it takes to make this recipe so scrumptious. From preparation to the plate, this recipe takes around <b>4 hours</b>. It is brought to you by BBC Good Food. With a spoonacular <b>score of 50%</b>, this dish is solid. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/frozen-peanut-butter-cup-dessert-pizza-treatzza-pizza-+-video-898671">Frozen Peanut Butter Cup Dessert Pizza (Treatzza Pizza) + VIDEO</a>, <a href="https://spoonacular.com/recipes/grilled-chicken-asparagus-and-mushroom-pizza-with-blackbird-bakery-pizza-crust-539911">Grilled Chicken, Asparagus, and Mushroom Pizza with Blackbird Bakery Pizza Crust</a>, and <a href="https://spoonacular.com/recipes/homemade-mellow-mushroom-pizza-dough-and-copy-cat-mellowterranean-pizza-569137">Homemade Mellow Mushroom Pizza Dough and Copy Cat Mellowterranean Pizza</a>.',
      cuisines: ["Mediterranean", "Italian", "European"],
      dishTypes: [],
      diets: ["lacto ovo vegetarian"],
      occasions: [],
      winePairing: {
        pairedWines: ["sangiovese", "barbera wine", "shiraz"],
        pairingText:
          "Sangiovese, Barbera Wine, and Shiraz are great choices for Pizza. The best wine for pizza depends on the toppings! Red sauce pizza will call for a red wine with some acidity, such as a barberan or sangiovese. Add pepperoni or sausage and you can go bolder with a syrah. The Fonterutoli Chianti Classico with a 4.3 out of 5 star rating seems like a good match. It costs about 8 dollars per bottle.",
        productMatches: [
          {
            id: 440954,
            title: "Fonterutoli Chianti Classico",
            description:
              "Color: Deep purplish-red but bright and exceptionally concentrated.Bouquet: Extremely intense and complex with scents of cherries and raspberries accompanied by light toasty and spicy shadings.Flavor: The impact in the mouth is incisive but soft due to a substantial structure of tannins in which those that are soft and well rounded stand out. Acidity is fused with the wine's body and aids the transmission of pleasant sensations of warmth and strength. The wine features a long finish that is unusual for a regular Chianti Classico.Conclusions: Those who argue that Chianti Classico is a prickly and rough wine will change their minds after tasting this 1999, which is ready to drink now but will improve for at least five years more.Alcohol: 13.5% by volume",
            price: "$7.99",
            imageUrl:
              "https://spoonacular.com/productImages/440954-312x231.jpg",
            averageRating: 0.86,
            ratingCount: 6.0,
            score: 0.8073684210526315,
            link:
              "https://click.linksynergy.com/deeplink?id=*QCiIS6t4gA&mid=2025&murl=https%3A%2F%2Fwww.wine.com%2Fproduct%2Ffonterutoli-chianti-classico-1998%2F12434",
          },
        ],
      },
      instructions:
        "Mix together the yeast and sugar with 250ml warm water and leave to sit for 10 mins. Place half the flour in a table-top mixer with a dough hook, pour in the yeast mixture and beat at medium speed for 10 mins (or mix in a bowl, then knead with oiled hands in the bowl for 5-10 mins).\nLeave somewhere warm for 10 more mins, then add the remaining flour and oil. Beat or knead to a dough for a further 5 mins. Put in a well-oiled bowl, cover with a cloth and place somewhere warm to double in size  about 1 hrs.\nFor the sauce, heat the oil in a pan over a moderate heat. Add the onion and cook for 3 mins, stirring constantly. Add the garlic, 1 tsp sea salt and 1 tsp ground black pepper and cook for 2 mins more. Add the tomatoes and bring to the boil, then reduce the heat and simmer for a good 20 mins, stirring occasionally.\nOnce your dough has doubled in size, slap it down on a lightly floured surface and knead for 4 mins until soft but not too elastic. Divide into 6 pieces, roll into balls and leave to rest for 10 mins. Heat oven to the highest temperature possible (270C fan in the Good Food test kitchen) and place a flat baking sheet in the oven.\nWith a well-floured rolling pin, roll out each ball of dough as thinly as possible. Remove the baking sheet from the oven, oil or dust with flour, then carefully transfer the dough base onto it. Spread over some of the tomato sauce (I like to apply it in the quantity that you would spread Marmite on toast, or the base will be soft and fall to bits), then the cheese and any toppings you desire.\nCook for between 5-10 mins depending on your oven temp, until the base is crisp and the cheese melted. Scatter with basil.",
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step:
                "Mix together the yeast and sugar with 250ml warm water and leave to sit for 10 mins.",
              ingredients: [
                {
                  id: 19335,
                  name: "sugar",
                  localizedName: "sugar",
                  image: "sugar-in-bowl.png",
                },
                {
                  id: 14412,
                  name: "water",
                  localizedName: "water",
                  image: "water.png",
                },
                {
                  id: 18375,
                  name: "yeast",
                  localizedName: "yeast",
                  image: "yeast-granules.jpg",
                },
              ],
              equipment: [],
              length: { number: 10, unit: "minutes" },
            },
            {
              number: 2,
              step:
                "Place half the flour in a table-top mixer with a dough hook, pour in the yeast mixture and beat at medium speed for 10 mins (or mix in a bowl, then knead with oiled hands in the bowl for 5-10 mins).",
              ingredients: [
                {
                  id: 0,
                  name: "dough",
                  localizedName: "dough",
                  image: "pizza-dough",
                },
                {
                  id: 20081,
                  name: "all purpose flour",
                  localizedName: "all purpose flour",
                  image: "flour.png",
                },
                {
                  id: 18375,
                  name: "yeast",
                  localizedName: "yeast",
                  image: "yeast-granules.jpg",
                },
              ],
              equipment: [
                {
                  id: 404726,
                  name: "blender",
                  localizedName: "blender",
                  image: "blender.png",
                },
                {
                  id: 404783,
                  name: "bowl",
                  localizedName: "bowl",
                  image: "bowl.jpg",
                },
              ],
              length: { number: 20, unit: "minutes" },
            },
            {
              number: 3,
              step:
                "Leave somewhere warm for 10 more mins, then add the remaining flour and oil. Beat or knead to a dough for a further 5 mins. Put in a well-oiled bowl, cover with a cloth and place somewhere warm to double in size  about 1 hrs.",
              ingredients: [
                {
                  id: 0,
                  name: "dough",
                  localizedName: "dough",
                  image: "pizza-dough",
                },
                {
                  id: 20081,
                  name: "all purpose flour",
                  localizedName: "all purpose flour",
                  image: "flour.png",
                },
                {
                  id: 4582,
                  name: "cooking oil",
                  localizedName: "cooking oil",
                  image: "vegetable-oil.jpg",
                },
              ],
              equipment: [
                {
                  id: 404783,
                  name: "bowl",
                  localizedName: "bowl",
                  image: "bowl.jpg",
                },
              ],
              length: { number: 15, unit: "minutes" },
            },
            {
              number: 4,
              step:
                "For the sauce, heat the oil in a pan over a moderate heat.",
              ingredients: [
                { id: 0, name: "sauce", localizedName: "sauce", image: "" },
                {
                  id: 4582,
                  name: "cooking oil",
                  localizedName: "cooking oil",
                  image: "vegetable-oil.jpg",
                },
              ],
              equipment: [
                {
                  id: 404645,
                  name: "frying pan",
                  localizedName: "frying pan",
                  image: "pan.png",
                },
              ],
            },
            {
              number: 5,
              step: "Add the onion and cook for 3 mins, stirring constantly.",
              ingredients: [
                {
                  id: 11282,
                  name: "onion",
                  localizedName: "onion",
                  image: "brown-onion.png",
                },
              ],
              equipment: [],
              length: { number: 3, unit: "minutes" },
            },
            {
              number: 6,
              step:
                "Add the garlic, 1 tsp sea salt and 1 tsp ground black pepper and cook for 2 mins more.",
              ingredients: [
                {
                  id: 1002030,
                  name: "ground black pepper",
                  localizedName: "ground black pepper",
                  image: "pepper.jpg",
                },
                {
                  id: 1012047,
                  name: "sea salt",
                  localizedName: "sea salt",
                  image: "salt.jpg",
                },
                {
                  id: 11215,
                  name: "garlic",
                  localizedName: "garlic",
                  image: "garlic.png",
                },
              ],
              equipment: [],
              length: { number: 2, unit: "minutes" },
            },
            {
              number: 7,
              step:
                "Add the tomatoes and bring to the boil, then reduce the heat and simmer for a good 20 mins, stirring occasionally.",
              ingredients: [
                {
                  id: 11529,
                  name: "tomato",
                  localizedName: "tomato",
                  image: "tomato.png",
                },
              ],
              equipment: [],
              length: { number: 20, unit: "minutes" },
            },
            {
              number: 8,
              step:
                "Once your dough has doubled in size, slap it down on a lightly floured surface and knead for 4 mins until soft but not too elastic. Divide into 6 pieces, roll into balls and leave to rest for 10 mins.",
              ingredients: [
                {
                  id: 0,
                  name: "dough",
                  localizedName: "dough",
                  image: "pizza-dough",
                },
                {
                  id: 0,
                  name: "roll",
                  localizedName: "roll",
                  image: "dinner-yeast-rolls.jpg",
                },
              ],
              equipment: [],
              length: { number: 14, unit: "minutes" },
            },
            {
              number: 9,
              step:
                "Heat oven to the highest temperature possible (270C fan in the Good Food test kitchen) and place a flat baking sheet in the oven.",
              ingredients: [],
              equipment: [
                {
                  id: 404727,
                  name: "baking sheet",
                  localizedName: "baking sheet",
                  image: "baking-sheet.jpg",
                },
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                  temperature: { number: 270.0, unit: "Celsius" },
                },
              ],
            },
            {
              number: 10,
              step:
                "With a well-floured rolling pin, roll out each ball of dough as thinly as possible.",
              ingredients: [
                {
                  id: 0,
                  name: "dough",
                  localizedName: "dough",
                  image: "pizza-dough",
                },
                {
                  id: 0,
                  name: "roll",
                  localizedName: "roll",
                  image: "dinner-yeast-rolls.jpg",
                },
              ],
              equipment: [
                {
                  id: 404746,
                  name: "rolling pin",
                  localizedName: "rolling pin",
                  image: "rolling-pin.jpg",
                },
              ],
            },
            {
              number: 11,
              step:
                "Remove the baking sheet from the oven, oil or dust with flour, then carefully transfer the dough base onto it.",
              ingredients: [
                {
                  id: 0,
                  name: "dough",
                  localizedName: "dough",
                  image: "pizza-dough",
                },
                {
                  id: 20081,
                  name: "all purpose flour",
                  localizedName: "all purpose flour",
                  image: "flour.png",
                },
                { id: 0, name: "base", localizedName: "base", image: "" },
                {
                  id: 4582,
                  name: "cooking oil",
                  localizedName: "cooking oil",
                  image: "vegetable-oil.jpg",
                },
              ],
              equipment: [
                {
                  id: 404727,
                  name: "baking sheet",
                  localizedName: "baking sheet",
                  image: "baking-sheet.jpg",
                },
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                },
              ],
            },
            {
              number: 12,
              step:
                "Spread over some of the tomato sauce (I like to apply it in the quantity that you would spread Marmite on toast, or the base will be soft and fall to bits), then the cheese and any toppings you desire.",
              ingredients: [
                {
                  id: 11549,
                  name: "tomato sauce",
                  localizedName: "tomato sauce",
                  image: "tomato-sauce-or-pasta-sauce.jpg",
                },
                {
                  id: 43406,
                  name: "marmite",
                  localizedName: "marmite",
                  image: "",
                },
                {
                  id: 1041009,
                  name: "cheese",
                  localizedName: "cheese",
                  image: "cheddar-cheese.png",
                },
                { id: 0, name: "spread", localizedName: "spread", image: "" },
                {
                  id: 18070,
                  name: "toast",
                  localizedName: "toast",
                  image: "toast",
                },
                { id: 0, name: "base", localizedName: "base", image: "" },
              ],
              equipment: [],
            },
            {
              number: 13,
              step:
                "Cook for between 5-10 mins depending on your oven temp, until the base is crisp and the cheese melted. Scatter with basil.",
              ingredients: [
                {
                  id: 1041009,
                  name: "cheese",
                  localizedName: "cheese",
                  image: "cheddar-cheese.png",
                },
                {
                  id: 2044,
                  name: "basil",
                  localizedName: "basil",
                  image: "basil.jpg",
                },
                { id: 0, name: "base", localizedName: "base", image: "" },
              ],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                },
              ],
              length: { number: 10, unit: "minutes" },
            },
          ],
        },
      ],
      originalId: null,
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      weightWatcherSmartPoints: 19,
      gaps: "no",
      lowFodmap: false,
      preparationMinutes: 25,
      cookingMinutes: 5,
      aggregateLikes: 20,
      spoonacularScore: 89.0,
      healthScore: 40.0,
      creditsText: "The Lean Green Bean",
      sourceName: "The Lean Green Bean",
      pricePerServing: 433.42,
      extendedIngredients: [
        {
          id: 16070,
          aisle: "Pasta and Rice;Canned and Jarred",
          image: "lentils-brown.jpg",
          consistency: "solid",
          name: "cooked lentils",
          original: "½ c lentils, cooked",
          originalString: "½ c lentils, cooked",
          originalName: "lentils, cooked",
          amount: 0.5,
          unit: "c",
          meta: ["cooked"],
          metaInformation: ["cooked"],
          measures: {
            us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
            metric: {
              amount: 118.294,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 2015,
          aisle: "Spices and Seasonings",
          image: "curry-powder.jpg",
          consistency: "solid",
          name: "curry powder",
          original: "1-2 tsp curry powder",
          originalString: "1-2 tsp curry powder",
          originalName: "curry powder",
          amount: 1.0,
          unit: "tsp",
          meta: [],
          metaInformation: [],
          measures: {
            us: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
            metric: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
          },
        },
        {
          id: 11216,
          aisle: "Produce;Ethnic Foods;Spices and Seasonings",
          image: "ginger.png",
          consistency: "solid",
          name: "fresh ginger",
          original: "1-2 tsp grated fresh ginger",
          originalString: "1-2 tsp grated fresh ginger",
          originalName: "grated fresh ginger",
          amount: 1.0,
          unit: "tsp",
          meta: ["fresh", "grated"],
          metaInformation: ["fresh", "grated"],
          measures: {
            us: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
            metric: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
          },
        },
        {
          id: 1159,
          aisle: "Cheese",
          image: "goat-cheese.jpg",
          consistency: "solid",
          name: "goat cheese",
          original: "goat cheese, crumbled",
          originalString: "goat cheese, crumbled",
          originalName: "goat cheese, crumbled",
          amount: 2.0,
          unit: "servings",
          meta: ["crumbled"],
          metaInformation: ["crumbled"],
          measures: {
            us: { amount: 2.0, unitShort: "servings", unitLong: "servings" },
            metric: {
              amount: 2.0,
              unitShort: "servings",
              unitLong: "servings",
            },
          },
        },
        {
          id: 11246,
          aisle: "Produce",
          image: "leeks.jpg",
          consistency: "solid",
          name: "leeks",
          original: "½ c chopped leeks",
          originalString: "½ c chopped leeks",
          originalName: "chopped leeks",
          amount: 0.5,
          unit: "c",
          meta: ["chopped"],
          metaInformation: ["chopped"],
          measures: {
            us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
            metric: {
              amount: 118.294,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 93723,
          aisle: "Bakery/Bread;Ethnic Foods",
          image: "naan.png",
          consistency: "solid",
          name: "naan",
          original: "2 pieces of naan",
          originalString: "2 pieces of naan",
          originalName: "naan",
          amount: 2.0,
          unit: "pieces",
          meta: [],
          metaInformation: [],
          measures: {
            us: { amount: 2.0, unitShort: "", unitLong: "" },
            metric: { amount: 2.0, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 10011298,
          aisle: "Produce",
          image: "root-vegetables.png",
          consistency: "solid",
          name: "root vegetables",
          original: "2 cups vegetables, diced (cauliflower, peppers, onion)",
          originalString:
            "2 cups vegetables, diced (cauliflower, peppers, onion)",
          originalName: "vegetables, diced (cauliflower, peppers, onion)",
          amount: 2.0,
          unit: "cups",
          meta: ["diced", "(cauliflower, peppers, onion)"],
          metaInformation: ["diced", "(cauliflower, peppers, onion)"],
          measures: {
            us: { amount: 2.0, unitShort: "cups", unitLong: "cups" },
            metric: {
              amount: 473.176,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 15152,
          aisle: "Seafood",
          image: "shrimp.png",
          consistency: "solid",
          name: "shrimp",
          original: "8-10 medium shrimp, cooked and chopped",
          originalString: "8-10 medium shrimp, cooked and chopped",
          originalName: "shrimp, cooked and chopped",
          amount: 8.0,
          unit: "medium",
          meta: ["cooked", "chopped"],
          metaInformation: ["cooked", "chopped"],
          measures: {
            us: { amount: 8.0, unitShort: "medium", unitLong: "mediums" },
            metric: { amount: 8.0, unitShort: "medium", unitLong: "mediums" },
          },
        },
        {
          id: 11507,
          aisle: "Produce",
          image: "sweet-potato.png",
          consistency: "solid",
          name: "sweet potato",
          original: "½ c curried sweet potato sauce",
          originalString: "½ c curried sweet potato sauce",
          originalName: "curried sweet potato sauce",
          amount: 0.5,
          unit: "c",
          meta: [],
          metaInformation: [],
          measures: {
            us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
            metric: {
              amount: 118.294,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 11507,
          aisle: "Produce",
          image: "sweet-potato.png",
          consistency: "solid",
          name: "sweet potato",
          original: "1 sweet potato, roughly chopped",
          originalString: "1 sweet potato, roughly chopped",
          originalName: "sweet potato, roughly chopped",
          amount: 1.0,
          unit: "",
          meta: ["roughly chopped"],
          metaInformation: ["roughly chopped"],
          measures: {
            us: { amount: 1.0, unitShort: "", unitLong: "" },
            metric: { amount: 1.0, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 6615,
          aisle: "Canned and Jarred",
          image: "chicken-broth.png",
          consistency: "liquid",
          name: "vegetable broth",
          original: "¾ c vegetable broth",
          originalString: "¾ c vegetable broth",
          originalName: "vegetable broth",
          amount: 0.75,
          unit: "c",
          meta: [],
          metaInformation: [],
          measures: {
            us: { amount: 0.75, unitShort: "cups", unitLong: "cups" },
            metric: {
              amount: 177.441,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
      ],
      id: 565588,
      title: "Indian Pizza",
      readyInMinutes: 30,
      servings: 2,
      sourceUrl: "http://www.theleangreenbean.com/indian-pizza/",
      image: "https://spoonacular.com/recipeImages/565588-556x370.jpg",
      imageType: "jpg",
      summary:
        'Indian Pizza might be just the main course you are searching for. One serving contains <b>758 calories</b>, <b>33g of protein</b>, and <b>18g of fat</b>. For <b>$4.51 per serving</b>, this recipe <b>covers 30%</b> of your daily requirements of vitamins and minerals. This recipe is typical of Indian cuisine. A few people made this recipe, and 20 would say it hit the spot. A mixture of shrimp, curry powder, sweet potato, and a handful of other ingredients are all it takes to make this recipe so tasty. To use up the curry powder you could follow this main course with the <a href="https://spoonacular.com/recipes/curry-ice-cream-with-mango-and-pistachio-539368">Curry Ice Cream with Mango and Pistachio</a> as a dessert. It is a good option if you\'re following a <b>pescatarian</b> diet. From preparation to the plate, this recipe takes roughly <b>30 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 89%</b>. This score is great. Try <a href="https://spoonacular.com/recipes/indian-cauliflower-pizza-579802">Indian Cauliflower Pizza</a>, <a href="https://spoonacular.com/recipes/indian-spiced-pita-pizza-46351">Indian Spiced Pita Pizza</a>, and <a href="https://spoonacular.com/recipes/indian-style-paneer-pizza-578239">Indian style paneer pizza</a> for similar recipes.',
      cuisines: ["Indian", "Asian"],
      dishTypes: ["lunch", "main course", "main dish", "dinner"],
      diets: ["pescatarian"],
      occasions: [],
      winePairing: {
        pairedWines: ["riesling", "gewurztraminer", "chenin blanc"],
        pairingText:
          "Asian works really well with Riesling, Gewurztraminer, and Chenin Blanc. The best wine for Asian food depends on the cuisine and dish - of course - but these acidic whites pair with a number of traditional meals, spicy or not. The Biltmore Estate Riesling with a 4.7 out of 5 star rating seems like a good match. It costs about 13 dollars per bottle.",
        productMatches: [
          {
            id: 428467,
            title: "Biltmore Estate Riesling",
            description:
              "Beautifully balanced with sweet apricot aromas, light honey flavors, and a crisp finish.",
            price: "$13.0",
            imageUrl:
              "https://spoonacular.com/productImages/428467-312x231.jpg",
            averageRating: 0.9400000000000001,
            ratingCount: 4.0,
            score: 0.8630769230769231,
            link:
              "https://www.amazon.com/Biltmore-Estate-Riesling-750-mL/dp/B01FDZUPZG?tag=spoonacular-20",
          },
        ],
      },
      instructions:
        "For the SauceAdd a little EVOO to a pan and saute leeks over medium heat until soft.Add the chopped sweet potato, broth and spices and bring to a boil.Reduce heat and simmer until sweet potatoes are tender.Transfer mixture to a blender or use an immersion blender and blend until smooth.Add more broth if necessary to thin out the sauce and adjust spices to taste.For the PizzaToss vegetables lightly in EVOO and season with curry powder. Roast at 400 degrees until desired tenderness is reached. Remove from oven.If using frozen naan, cook at 400 degrees for 5-6 minutes to heat through. Remove from oven.Spread sauce onto naan pieces.Top with lentils.Add roasted vegetables and chopped shrimp.Top with crumbles of goat cheese.Bake for 6-8 minuts until heated through.",
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step: "For the Sauce",
              ingredients: [
                { id: 0, name: "sauce", localizedName: "sauce", image: "" },
              ],
              equipment: [],
            },
            {
              number: 2,
              step:
                "Add a little EVOO to a pan and saute leeks over medium heat until soft.",
              ingredients: [
                {
                  id: 11246,
                  name: "leek",
                  localizedName: "leek",
                  image: "leeks.jpg",
                },
                {
                  id: 1034053,
                  name: "extra virgin olive oil",
                  localizedName: "extra virgin olive oil",
                  image: "olive-oil.jpg",
                },
              ],
              equipment: [
                {
                  id: 404645,
                  name: "frying pan",
                  localizedName: "frying pan",
                  image: "pan.png",
                },
              ],
            },
            {
              number: 3,
              step:
                "Add the chopped sweet potato, broth and spices and bring to a boil.Reduce heat and simmer until sweet potatoes are tender.",
              ingredients: [
                {
                  id: 11507,
                  name: "sweet potato",
                  localizedName: "sweet potato",
                  image: "sweet-potato.png",
                },
                {
                  id: 2035,
                  name: "spices",
                  localizedName: "spices",
                  image: "spices.png",
                },
                {
                  id: 1006615,
                  name: "broth",
                  localizedName: "broth",
                  image: "chicken-broth.png",
                },
              ],
              equipment: [],
            },
            {
              number: 4,
              step:
                "Transfer mixture to a blender or use an immersion blender and blend until smooth.",
              ingredients: [],
              equipment: [
                {
                  id: 404776,
                  name: "immersion blender",
                  localizedName: "immersion blender",
                  image: "immersion-blender.png",
                },
                {
                  id: 404726,
                  name: "blender",
                  localizedName: "blender",
                  image: "blender.png",
                },
              ],
            },
            {
              number: 5,
              step:
                "Add more broth if necessary to thin out the sauce and adjust spices to taste.For the Pizza",
              ingredients: [
                {
                  id: 2035,
                  name: "spices",
                  localizedName: "spices",
                  image: "spices.png",
                },
                {
                  id: 1006615,
                  name: "broth",
                  localizedName: "broth",
                  image: "chicken-broth.png",
                },
                { id: 0, name: "sauce", localizedName: "sauce", image: "" },
              ],
              equipment: [],
            },
            {
              number: 6,
              step:
                "Toss vegetables lightly in EVOO and season with curry powder. Roast at 400 degrees until desired tenderness is reached.",
              ingredients: [
                {
                  id: 2015,
                  name: "curry powder",
                  localizedName: "curry powder",
                  image: "curry-powder.jpg",
                },
                {
                  id: 11583,
                  name: "vegetable",
                  localizedName: "vegetable",
                  image: "mixed-vegetables.png",
                },
                {
                  id: 1034053,
                  name: "extra virgin olive oil",
                  localizedName: "extra virgin olive oil",
                  image: "olive-oil.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 7,
              step:
                "Remove from oven.If using frozen naan, cook at 400 degrees for 5-6 minutes to heat through.",
              ingredients: [
                {
                  id: 93723,
                  name: "naan",
                  localizedName: "naan",
                  image: "naan.png",
                },
              ],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                },
              ],
              length: { number: 6, unit: "minutes" },
            },
            {
              number: 8,
              step: "Remove from oven.",
              ingredients: [],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                },
              ],
            },
            {
              number: 9,
              step: "Spread sauce onto naan pieces.Top with lentils.",
              ingredients: [
                {
                  id: 10316069,
                  name: "lentils",
                  localizedName: "lentils",
                  image: "lentils-brown.jpg",
                },
                { id: 0, name: "spread", localizedName: "spread", image: "" },
                { id: 0, name: "sauce", localizedName: "sauce", image: "" },
                {
                  id: 93723,
                  name: "naan",
                  localizedName: "naan",
                  image: "naan.png",
                },
              ],
              equipment: [],
            },
            {
              number: 10,
              step:
                "Add roasted vegetables and chopped shrimp.Top with crumbles of goat cheese.",
              ingredients: [
                {
                  id: 1159,
                  name: "goat cheese",
                  localizedName: "goat cheese",
                  image: "goat-cheese.jpg",
                },
                {
                  id: 11583,
                  name: "vegetable",
                  localizedName: "vegetable",
                  image: "mixed-vegetables.png",
                },
                {
                  id: 15152,
                  name: "shrimp",
                  localizedName: "shrimp",
                  image: "shrimp.png",
                },
              ],
              equipment: [],
            },
            {
              number: 11,
              step: "Bake for 6-8 minuts until heated through.",
              ingredients: [],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image: "oven.jpg",
                },
              ],
            },
          ],
        },
      ],
      originalId: null,
    },
  ],
};

export default food;
